// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package iie.grpc;

public interface ResultEntryHashOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResultEntryHash)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ResultEntry ResultEntries = 1;</code>
   */
  java.util.List<iie.grpc.ResultEntry> 
      getResultEntriesList();
  /**
   * <code>repeated .ResultEntry ResultEntries = 1;</code>
   */
  iie.grpc.ResultEntry getResultEntries(int index);
  /**
   * <code>repeated .ResultEntry ResultEntries = 1;</code>
   */
  int getResultEntriesCount();
  /**
   * <code>repeated .ResultEntry ResultEntries = 1;</code>
   */
  java.util.List<? extends iie.grpc.ResultEntryOrBuilder> 
      getResultEntriesOrBuilderList();
  /**
   * <code>repeated .ResultEntry ResultEntries = 1;</code>
   */
  iie.grpc.ResultEntryOrBuilder getResultEntriesOrBuilder(
      int index);
}
