// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vector.proto

package iie.grpc;

public interface VectorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VectorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .MediaTask&gt; batchVector = 1;</code>
   */
  int getBatchVectorCount();
  /**
   * <code>map&lt;string, .MediaTask&gt; batchVector = 1;</code>
   */
  boolean containsBatchVector(
      java.lang.String key);
  /**
   * Use {@link #getBatchVectorMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, iie.grpc.MediaTask>
  getBatchVector();
  /**
   * <code>map&lt;string, .MediaTask&gt; batchVector = 1;</code>
   */
  java.util.Map<java.lang.String, iie.grpc.MediaTask>
  getBatchVectorMap();
  /**
   * <code>map&lt;string, .MediaTask&gt; batchVector = 1;</code>
   */

  iie.grpc.MediaTask getBatchVectorOrDefault(
      java.lang.String key,
      iie.grpc.MediaTask defaultValue);
  /**
   * <code>map&lt;string, .MediaTask&gt; batchVector = 1;</code>
   */

  iie.grpc.MediaTask getBatchVectorOrThrow(
      java.lang.String key);
}
